// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3mxkKWGeDqyEOA7MAmZm2q2I6OJ6Os0M',
    appId: '1:706189234663:android:8a676a0b27c913bc1c6d42',
    messagingSenderId: '706189234663',
    projectId: 'storifuel-app',
    storageBucket: 'storifuel-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc9-jVxPg6qaMYhl-jpxCVfWfDlw_BAJs',
    appId: '1:706189234663:ios:3ec1f2c3cdf502621c6d42',
    messagingSenderId: '706189234663',
    projectId: 'storifuel-app',
    storageBucket: 'storifuel-app.firebasestorage.app',
    iosBundleId: 'com.company.storifuel',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX1OfNpMeW04c01ttOaD5_zx8fCkSpmnk',
    appId: '1:706189234663:web:682428eabbfc763a1c6d42',
    messagingSenderId: '706189234663',
    projectId: 'storifuel-app',
    authDomain: 'storifuel-app.firebaseapp.com',
    storageBucket: 'storifuel-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX1OfNpMeW04c01ttOaD5_zx8fCkSpmnk',
    appId: '1:706189234663:web:c4e9fd69980f2bc11c6d42',
    messagingSenderId: '706189234663',
    projectId: 'storifuel-app',
    authDomain: 'storifuel-app.firebaseapp.com',
    storageBucket: 'storifuel-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc9-jVxPg6qaMYhl-jpxCVfWfDlw_BAJs',
    appId: '1:706189234663:ios:14757bf91f2941d81c6d42',
    messagingSenderId: '706189234663',
    projectId: 'storifuel-app',
    storageBucket: 'storifuel-app.firebasestorage.app',
    iosBundleId: 'com.example.storifuel',
  );

}